"""initial schema

Revision ID: 7256164dbda7
Revises: 
Create Date: 2026-08-28 17:16:34.410403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7256164dbda7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modifiers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_scenarios_key'), 'simulation_scenarios', ['key'], unique=True)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_synthetic_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('affected_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommended_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_station_id'), 'alerts', ['station_id'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='anomalyseverity'), nullable=False),
    sa.Column('affected_asset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('deviation_pct', sa.Float(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_station_id'), 'anomalies', ['station_id'], unique=False)
    op.create_index(op.f('ix_anomalies_timestamp'), 'anomalies', ['timestamp'], unique=False)
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capacity_kwh', sa.Float(), nullable=False),
    sa.Column('max_charge_rate_kw', sa.Float(), nullable=False),
    sa.Column('max_discharge_rate_kw', sa.Float(), nullable=False),
    sa.Column('min_soc_pct', sa.Float(), nullable=False),
    sa.Column('max_soc_pct', sa.Float(), nullable=False),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('health_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batteries_station_id'), 'batteries', ['station_id'], unique=False)
    op.create_table('energy_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('demand_kw', sa.Float(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_consumption_station_id'), 'energy_consumption', ['station_id'], unique=False)
    op.create_index(op.f('ix_energy_consumption_timestamp'), 'energy_consumption', ['timestamp'], unique=False)
    op.create_table('energy_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('SOLAR', 'WIND', 'BATTERY', 'GENERATOR', name='energysourcetype'), nullable=False),
    sa.Column('rated_capacity_kw', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_sources_station_id'), 'energy_sources', ['station_id'], unique=False)
    op.create_table('generators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rated_capacity_kw', sa.Float(), nullable=False),
    sa.Column('fuel_tank_capacity_l', sa.Float(), nullable=False),
    sa.Column('fuel_consumption_l_per_kwh', sa.Float(), nullable=False),
    sa.Column('co2_kg_per_l_diesel', sa.Float(), nullable=False),
    sa.Column('last_maintenance_at', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance_due_hours', sa.Float(), nullable=False),
    sa.Column('runtime_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generators_station_id'), 'generators', ['station_id'], unique=False)
    op.create_table('loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'IMPORTANT', 'DEFERRABLE', 'NON_CRITICAL', name='loadpriority'), nullable=False),
    sa.Column('rated_power_kw', sa.Float(), nullable=False),
    sa.Column('is_deferrable', sa.Boolean(), nullable=False),
    sa.Column('is_shed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loads_station_id'), 'loads', ['station_id'], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_benefit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_results_generated_at'), 'optimization_results', ['generated_at'], unique=False)
    op.create_index(op.f('ix_optimization_results_station_id'), 'optimization_results', ['station_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.Enum('DEMAND', 'SOLAR', 'WIND', name='predictiontype'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('target_timestamp', sa.DateTime(), nullable=False),
    sa.Column('horizon_hours', sa.Float(), nullable=False),
    sa.Column('predicted_value_kw', sa.Float(), nullable=False),
    sa.Column('actual_value_kw', sa.Float(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_generated_at'), 'predictions', ['generated_at'], unique=False)
    op.create_index(op.f('ix_predictions_station_id'), 'predictions', ['station_id'], unique=False)
    op.create_index(op.f('ix_predictions_target_timestamp'), 'predictions', ['target_timestamp'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('summary_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_station_id'), 'reports', ['station_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('scenario_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_station_id'), 'simulation_runs', ['station_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'ADMIN', 'SCIENTIST', name='userrole'), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_station_id'), 'users', ['station_id'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=False),
    sa.Column('wind_speed_mps', sa.Float(), nullable=False),
    sa.Column('solar_irradiance_w_m2', sa.Float(), nullable=False),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=False),
    sa.Column('visibility_km', sa.Float(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_station_id'), 'weather_data', ['station_id'], unique=False)
    op.create_index(op.f('ix_weather_data_timestamp'), 'weather_data', ['timestamp'], unique=False)
    op.create_table('battery_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('soc_pct', sa.Float(), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=False),
    sa.Column('current_a', sa.Float(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battery_readings_battery_id'), 'battery_readings', ['battery_id'], unique=False)
    op.create_index(op.f('ix_battery_readings_timestamp'), 'battery_readings', ['timestamp'], unique=False)
    op.create_table('energy_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['energy_sources.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_readings_source_id'), 'energy_readings', ['source_id'], unique=False)
    op.create_index(op.f('ix_energy_readings_station_id'), 'energy_readings', ['station_id'], unique=False)
    op.create_index(op.f('ix_energy_readings_timestamp'), 'energy_readings', ['timestamp'], unique=False)
    op.create_table('generator_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generator_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'STANDBY', 'OFF', 'MAINTENANCE', 'FAULT', name='generatorstatus'), nullable=False),
    sa.Column('output_kw', sa.Float(), nullable=False),
    sa.Column('fuel_level_pct', sa.Float(), nullable=False),
    sa.Column('fuel_consumed_l', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['generator_id'], ['generators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generator_readings_generator_id'), 'generator_readings', ['generator_id'], unique=False)
    op.create_index(op.f('ix_generator_readings_timestamp'), 'generator_readings', ['timestamp'], unique=False)
    op.create_table('load_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_load_readings_load_id'), 'load_readings', ['load_id'], unique=False)
    op.create_index(op.f('ix_load_readings_timestamp'), 'load_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_load_readings_timestamp'), table_name='load_readings')
    op.drop_index(op.f('ix_load_readings_load_id'), table_name='load_readings')
    op.drop_table('load_readings')
    op.drop_index(op.f('ix_generator_readings_timestamp'), table_name='generator_readings')
    op.drop_index(op.f('ix_generator_readings_generator_id'), table_name='generator_readings')
    op.drop_table('generator_readings')
    op.drop_index(op.f('ix_energy_readings_timestamp'), table_name='energy_readings')
    op.drop_index(op.f('ix_energy_readings_station_id'), table_name='energy_readings')
    op.drop_index(op.f('ix_energy_readings_source_id'), table_name='energy_readings')
    op.drop_table('energy_readings')
    op.drop_index(op.f('ix_battery_readings_timestamp'), table_name='battery_readings')
    op.drop_index(op.f('ix_battery_readings_battery_id'), table_name='battery_readings')
    op.drop_table('battery_readings')
    op.drop_index(op.f('ix_weather_data_timestamp'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_station_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_users_station_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_simulation_runs_station_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_reports_station_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_predictions_target_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_station_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_generated_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_optimization_results_station_id'), table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_generated_at'), table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index(op.f('ix_loads_station_id'), table_name='loads')
    op.drop_table('loads')
    op.drop_index(op.f('ix_generators_station_id'), table_name='generators')
    op.drop_table('generators')
    op.drop_index(op.f('ix_energy_sources_station_id'), table_name='energy_sources')
    op.drop_table('energy_sources')
    op.drop_index(op.f('ix_energy_consumption_timestamp'), table_name='energy_consumption')
    op.drop_index(op.f('ix_energy_consumption_station_id'), table_name='energy_consumption')
    op.drop_table('energy_consumption')
    op.drop_index(op.f('ix_batteries_station_id'), table_name='batteries')
    op.drop_table('batteries')
    op.drop_index(op.f('ix_anomalies_timestamp'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_station_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_station_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('stations')
    op.drop_index(op.f('ix_simulation_scenarios_key'), table_name='simulation_scenarios')
    op.drop_table('simulation_scenarios')
    # ### end Alembic commands ###
